nrf_security: doc: Add PAKE algorithms
nrfconnect/sdk-nrfxlib pull request #1007
Opened 2023-05-31 12:21 UTC by vili-nordic

Adds information about the configuration of EC J-PAKE, SPAKE2+ and SRP to the documentation.

Ref: NCSDK-21788

2023-05-31 13:43 UTC, mia-ko requested changes

2023-05-31 13:43 UTC, mia-ko commented on nrf_security/doc/driver_config.rst
> +   * The algorithms are only available together with the nrf_oberon PSA Core :kconfig:option:`CONFIG_PSA_CORE_OBERON`.
```suggestion
   * The algorithms are only available together with the nrf_oberon PSA Core (:kconfig:option:`CONFIG_PSA_CORE_OBERON`).
```

2023-05-31 13:47 UTC, mia-ko requested changes

2023-06-01 07:23 UTC, joerchan commented on nrf_security/doc/driver_config.rst
> +.. note::
We should follow the pattern of having another subsection for driver configuration:

Password-authenticated key agreement driver configurations
And list the driver support.

2023-06-01 07:38 UTC, melwee01 commented
Agree with Mia's comments. I don't have anything else to add.

2023-06-01 09:00 UTC, mia-ko commented on nrf_security/doc/driver_config.rst
> +| Hash algorithm        | nrf_cc3xx driver support | nrf_oberon driver support                                     |
```suggestion
| PAKE algorithm        | nrf_cc3xx driver support | nrf_oberon driver support                                     |
```

2023-06-01 09:00 UTC, mia-ko commented on nrf_security/doc/driver_config.rst
> +You can use the following PSA driver-specific configurations for fine-grained control over which drivers provide Password-authenticated key agreement.
```suggestion
You can use the following PSA driver-specific configurations for fine-grained control over which drivers provide password-authenticated key agreement.
```

2023-06-01 10:37 UTC, joerchan approved these changes

2023-06-01 10:47 UTC, mia-ko approved these changes

2023-06-01 11:19 UTC, SebastianBoe commented
These commits are now in https://github.com/nrfconnect/sdk-nrfxlib/pull/1009

2023-06-01 11:19 UTC, closed without merging