CI: Update RS/FEM scope in test-spec.yaml
nrfconnect/sdk-nrfxlib pull request #1019
Opened 2023-06-09 06:10 UTC by dawidprzybylo

2023-06-09 07:18 UTC, e-rk requested changes

2023-06-09 07:18 UTC, e-rk commented on .github/test-spec.yml
> +  - "nrf_modem/**/*"f
```suggestion
  - "nrf_modem/**/*"
```

2023-06-09 07:18 UTC, e-rk commented on .github/test-spec.yml
> +  - "mpsl/CmakeLists.txt"
```suggestion
  - "mpsl/CMakeLists.txt"
```

2023-06-09 07:21 UTC, dawidprzybylo commented on .github/test-spec.yml
> +  - "nrf_modem/**/*"f
Fixed :)

2023-06-09 07:24 UTC, dawidprzybylo commented on .github/test-spec.yml
> +  - "mpsl/CmakeLists.txt"
Fixed :)

2023-06-09 07:24 UTC, dawidprzybylo commented on .github/test-spec.yml
> +  - "softdevice_controller/CmakeLists.txt"
Fixed :)

2023-06-09 07:24 UTC, dawidprzybylo commented on .github/test-spec.yml
> +  - "mpsl/CmakeLists.txt"
Fixed :)

2023-06-09 07:24 UTC, dawidprzybylo commented on .github/test-spec.yml
> +  - "softdevice_controller/CmakeLists.txt"
Fixed :)

2023-06-09 07:46 UTC, e-rk approved these changes

2023-06-09 07:51 UTC, jciupis approved these changes

2023-06-12 09:05 UTC, czeslawmakarski approved these changes

2023-06-12 14:20 UTC, merged