doc: crypto: Make the crypto docs aware of nrf9161
nrfconnect/sdk-nrfxlib pull request #1069
Opened 2023-08-28 14:47 UTC by SebastianBoe

Update crypto docs to refer to nrf91 instead of nrf9160 as nrf9161 is also supported now.

Also, update one place where nrf53 was omitted.

Only the most recent changelog is updated as changelogs do not really need to be updated. We only update the changelogs to make it easier to copy-paste the changelog on the next release.

2023-08-29 06:07 UTC, melwee01 requested changes

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc310_bl.rst
> +   * The cc310 libraries require the CryptoCell 310 HW accelerator, available on nRF52840 and nRF91 devices.
```suggestion
   * The cc310 libraries require the CryptoCell 310 HW accelerator, available on nRF52840 and nRF91 Series devices.
```

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc310_bl.rst
> +* nrf_cc310_bl, nrf91 variants:
```suggestion
* nrf_cc310_bl, nRF91 Series variants:
```

Unless these are written to display exactly as something in code, but then they should be styled some way.

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc3xx_mbedcrypto.rst
> +Added a new build of nRF_cc3xx_mbedcrypto libraries for nRF91, nRF52840, and nRF5340.
```suggestion
Added a new build of nRF_cc3xx_mbedcrypto libraries for nRF91 Series, nRF52840, and nRF5340.
```

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc3xx_mbedcrypto.rst
> +* nrf_cc310_mbedcrypto, nRF91 variants
```suggestion
* nrf_cc310_mbedcrypto, nRF91 Series variants
```

Regarding my comment above, I think the lowercase must've just been a typo, then.

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc3xx_platform.rst
> +Added a new build of nrf_cc3xx_platform libraries for nRF91, nRF52840, and nRF5340.
```suggestion
Added a new build of nrf_cc3xx_platform libraries for nRF91 Series, nRF52840, and nRF5340.
```

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc3xx_platform.rst
> +* nrf_cc310_platform, nRF91 variants
```suggestion
* nrf_cc310_platform, nRF91 Series variants
```

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_oberon.rst
> +Added the following Oberon crypto libraries for nRF91, nRF53, nRF52, and nRF51 architectures.
Hmm. Wonder if since these are all also nRFxx Series, there should just be a Series at the very end.

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_oberon.rst
> +Added the following Oberon crypto libraries for nRF91, nRF53, nRF52, and nRF51 architectures.
```suggestion
Added the following Oberon crypto libraries for nRF91, nRF53, nRF52, and nRF51 Series.
```
Like so. Not sure.

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/nrf_cc310_bl.rst
> +   Note that the structure type for the CryptoCell hardware register is called ``NRF_CRYPTOCELL_S`` in nRF91 due to the hardware only being accessible from the Secure Processing Environment in the Co
```suggestion
   Note that the structure type for the CryptoCell hardware register is called ``NRF_CRYPTOCELL_S`` in nRF91 Series devices, due to the hardware only being accessible from the Secure Processing Environment in the Cortex-M33 architecture.
```

2023-08-29 06:07 UTC, melwee01 commented on crypto/doc/CHANGELOG_oberon.rst
> +* nrf_oberon, nRF91 and nRF53 application core variants
```suggestion
* nrf_oberon, nRF91 and nRF53 Series application core variants
```

2023-08-29 08:55 UTC, mswarowsky approved these changes
lgtm

2023-08-29 09:40 UTC, melwee01 commented on crypto/doc/CHANGELOG_cc3xx_mbedcrypto.rst
> +* nrf_cc310_mbedcrypto, nRF91 variants
```suggestion
* nrf_cc310_mbedcrypto, nRF91 Series variants
```

to align with the cc3xx platform changelog.

2023-08-29 09:41 UTC, melwee01 approved these changes

2023-08-29 11:42 UTC, mia-ko requested changes

2023-08-29 11:42 UTC, mia-ko commented on crypto/doc/nrf_cc310_bl.rst
> +The nrf_cc310_bl library is a software library to interface with Arm CryptoCell CC310 hardware accelerator that is available on the nRF52840 SoC and the nRF91 SoC series.
```suggestion
The nrf_cc310_bl library is a software library to interface with Arm CryptoCell CC310 hardware accelerator that is available on the nRF52840 SoC and the nRF91 Series.
```

2023-08-29 11:42 UTC, mia-ko commented on crypto/doc/nrf_cc3xx_mbedcrypto.rst
> +The nrf_cc3xx_mbedcrypto library is software library to interface with the Arm CryptoCell hardware accelerator that is available on the nRF52840 SoC, the nRF53 SoC series, and the nRF91 SoC series.
```suggestion
The nrf_cc3xx_mbedcrypto library is software library to interface with the Arm CryptoCell hardware accelerator that is available on the nRF52840 SoC, the nRF53 Series, and the nRF91 Series.
```

2023-08-29 11:42 UTC, mia-ko commented on crypto/doc/nrf_cc3xx_mbedcrypto.rst
> +The following tables show the the current state of support.
```suggestion
The following tables show the current state of support.
```

2023-08-29 11:42 UTC, mia-ko commented on crypto/doc/nrf_cc3xx_platform.rst
> +The nrf_cc3xx_platform library is software library to interface with the Arm CryptoCell CC310/CC312 hardware accelerator that is available on the nRF52840 SoC, the nRF53 SoC series, and the nRF91 SoC
```suggestion
The nrf_cc3xx_platform library is software library to interface with the Arm CryptoCell CC310/CC312 hardware accelerator that is available on the nRF52840 SoC, the nRF53 Series, and the nRF91 Series.
```

2023-09-12 07:29 UTC, Vge0rge approved these changes

2023-09-12 11:38 UTC, merged