Move Wi-Fi OS agnostic code from sdk-nrf
nrfconnect/sdk-nrfxlib pull request #1101
Opened 2023-10-23 15:32 UTC by krish2718

Long pending item for moving all OS agnostic code out of sdk-nrf, I have moved the commits to preserver the history, but this means that same commit now exists in two places `sdk-nrf` (before deletion of OSAL) and in this repo.

2023-10-23 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=1101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=1101) before we can accept your contribution.<br/>**2** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: krish2718<br/>:white_check_mark: umapraseeda<br/>:x: kapbh<br/>:x: kspraveeen<br/>:x: sachinthegreen<br/>:x: prsi98<br/>:x: ajayparida<br/>:x: VivekUppunda<br/>:x: srinivas1201<br/>:x: chiranjeevi2776<br/>:x: ditt-nordic<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrfxlib?pullRequest=1101) it.</sub>

2023-10-23 15:44 UTC, kapbh approved these changes

2023-10-25 07:18 UTC, VivekUppunda approved these changes

2023-10-25 10:25 UTC, rlubos approved these changes

2023-10-26 08:03 UTC, richabp requested changes

2023-10-26 08:03 UTC, richabp commented on nrf_wifi/doc/low_api_common.rst
> +------
```suggestion
Common
######
```

2023-10-26 08:03 UTC, richabp commented on nrf_wifi/doc/low_api_radio_test.rst
> +---------------
```suggestion
Radio Test mode
###############
```

2023-10-26 08:03 UTC, richabp commented on nrf_wifi/doc/low_api_wifi.rst
> +----------
```suggestion
Wi-Fi mode
##########
```

2023-10-26 14:03 UTC, richabp approved these changes

2023-10-27 07:32 UTC, merged