nrf_wifi: doc: Add a prefix
nrfconnect/sdk-nrfxlib pull request #1114
Opened 2023-11-07 13:45 UTC by krish2718

In the ToC a prefix helps disambiguate.

2023-11-07 15:06 UTC, richabp requested changes

2023-11-07 15:06 UTC, richabp commented on nrf_wifi/README.rst
> +nRF70 Low-level API documentation
```suggestion
nRF70 low-level API documentation
```

2023-11-07 19:34 UTC, richabp approved these changes

2023-11-08 12:12 UTC, sachinthegreen approved these changes

2023-11-08 12:24 UTC, merged