Remove raw tx config check for mode
nrfconnect/sdk-nrfxlib pull request #1180
Opened 2024-01-25 03:35 UTC by VivekUppunda

Remove RAW tx config check for setting mode. Also, remove a redundant declaration in fmac_util.h

2024-01-27 10:28 UTC, krish2718 approved these changes

2024-01-29 05:45 UTC, kapbh approved these changes

2024-01-29 06:30 UTC, rado17 approved these changes

2024-01-29 07:15 UTC, sachinthegreen approved these changes

2024-01-29 07:18 UTC, sachinthegreen requested changes
Please raise a manifest PR in https://github.com/NordicPlayground/nrf70-linux-driver too.

2024-01-29 07:26 UTC, krga2022 approved these changes

2024-01-29 07:43 UTC, VivekUppunda commented
> Please raise a manifest PR in https://github.com/NordicPlayground/nrf70-linux-driver too.

I have raised the NordicPlayground PR 
https://github.com/NordicPlayground/nrf70-linux-driver/pull/48
checking build

2024-01-29 08:14 UTC, sachinthegreen approved these changes

2024-01-29 10:03 UTC, merged