nrf_wifi: Update RPU patch to rev#62892d9f23c
nrfconnect/sdk-nrfxlib pull request #1186
Opened 2024-01-29 07:33 UTC by karun2796

UMAC:
     Updated RPU patch version fropm 1.2.9.8 to 1.2.9.9.
     [SHEL-2394] : Updating Mismatched TX done statistics in SAP mode.
     [SHEL-2298] : Monitor mode support in UMAC.

LMAC:
     [SHEL-2397] : Proper rate flags updation in Rx event from LMAC.

2024-01-29 08:13 UTC, sachinthegreen requested changes
Please raise manifest PRs in :

https://github.com/nrfconnect/sdk-nrf and,
https://github.com/NordicPlayground/nrf70-linux-driver

2024-01-29 08:13 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_data_if.h
> +	/** refer see &enum rpu_tput_mode */
/** Refer @enum rpu_tput_mode */

2024-01-29 08:13 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_data_if.h
> +	 *		  11N VHT HE  : MCS index 0 to 7.
```
/** Rate: Legacy : 1, 2, 55, 6, 9, 11, 12, 18, 24, 36, 48, 54
  *       11N VHT HE  : MCS index 0 to 7.
```

2024-01-29 10:03 UTC, karun2796 commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_data_if.h
> +	 *		  11N VHT HE  : MCS index 0 to 7.
Taken Care

2024-01-29 10:03 UTC, karun2796 commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_data_if.h
> +	/** refer see &enum rpu_tput_mode */
Taken care

2024-01-29 10:15 UTC, rajb9 approved these changes

2024-01-29 10:25 UTC, udaynordic approved these changes

2024-01-29 10:29 UTC, karun2796 commented
> Please raise manifest PRs in :
> 
> https://github.com/nrfconnect/sdk-nrf and, https://github.com/NordicPlayground/nrf70-linux-driver

Raised

2024-01-30 11:29 UTC, sachinthegreen approved these changes

2024-01-30 11:49 UTC, merged