nrf_wifi: RPU expects wlan0 as the device name
nrfconnect/sdk-nrfxlib pull request #1198
Opened 2024-02-05 11:18 UTC by rado17

Map the Wi-Fi device name to "wlan0", since thats the requirement from RPU.

2024-02-05 13:56 UTC, krish2718 requested changes

2024-02-05 13:56 UTC, krish2718 commented on nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
> +
wrong indent

2024-02-05 13:56 UTC, krish2718 commented on nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
> +	char ifname[8] = "wlan0";
This should be in the UMAC headers

2024-02-15 10:37 UTC, sachinthegreen approved these changes

2024-02-15 11:50 UTC, krish2718 approved these changes

2024-02-21 11:22 UTC, rado17 commented
Changes merged as part of https://github.com/nrfconnect/sdk-nrfxlib/commit/1422e8d21ad3fa0accafb292a7d2ba6e27673ed2. Closing this PR.

2024-02-21 11:22 UTC, closed without merging