nrf_wifi: Support for CSP package in Host driver
nrfconnect/sdk-nrfxlib pull request #1199
Opened 2024-02-06 10:03 UTC by imapa

[SHEL-2310]: Modify host driver to read package type from OTP. Use this package type information to pick RF parameters.

2024-02-06 10:15 UTC, krish2718 approved these changes

2024-02-06 11:35 UTC, sachinthegreen requested changes

2024-02-06 11:35 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +						  &package_info);
Fix indentation

2024-02-06 11:35 UTC, sachinthegreen commented on nrf_wifi/hw_if/hal/inc/hal_api.h
> +						    						unsigned int *package_info);
Fix indentation

2024-02-06 12:10 UTC, imapa commented on nrf_wifi/hw_if/hal/src/hal_api.c
> +						    						unsigned int *package_info)
Done

2024-02-06 12:10 UTC, imapa commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +						  &package_info);
Done

2024-02-06 12:11 UTC, imapa commented on nrf_wifi/hw_if/hal/inc/hal_api.h
> +						    						unsigned int *package_info);
Done.

2024-02-07 12:22 UTC, imapa commented
> manifest PR in NordicPlayground ?

https://github.com/NordicPlayground/nrf70-linux-driver/pull/57

2024-02-07 13:01 UTC, merged