nrf_wifi: Rename occurrences of bt*/ble* to sr*/SR*
nrfconnect/sdk-nrfxlib pull request #1204
Opened 2024-02-09 11:37 UTC by muraliThokala

SHEL-2395: Rename all occurrences of ble*/BLE*/bt*/BT* to sr*/SR* to have generic names in common code, to support coexistence with Short Range radios.

2024-02-09 11:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=1204) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=1204) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrfxlib?pullRequest=1204) it.</sub>

2024-02-12 09:58 UTC, krish2718 approved these changes

2024-02-12 12:40 UTC, rado17 approved these changes

2024-02-12 13:07 UTC, sachinthegreen requested changes

2024-02-12 13:07 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
> +#ifdef CONFIG_NRF700X_RAW_DATA_TX
Why this change?

2024-02-12 13:07 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
> +#endif /* CONFIG_NRF700X_RAW_DATA_TX */
Why this change?

2024-02-12 13:07 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#ifdef CONFIG_NRF700X_RAW_DATA_TX
Why this change?

2024-02-12 13:07 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#endif /* CONFIG_NRF700X_RAW_DATA_TX */
Why this change?

2024-02-12 13:37 UTC, muraliThokala commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#endif /* CONFIG_NRF700X_RAW_DATA_TX */
corrected.

2024-02-12 13:37 UTC, muraliThokala commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#ifdef CONFIG_NRF700X_RAW_DATA_TX
corrected.

2024-02-12 13:37 UTC, muraliThokala commented on nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
> +#endif /* CONFIG_NRF700X_RAW_DATA_TX */
corrected.

2024-02-14 08:50 UTC, sachinthegreen approved these changes

2024-02-14 12:44 UTC, merged