doc: Documentation fixes
nrfconnect/sdk-nrfxlib pull request #1232
Opened 2024-02-27 13:08 UTC by umapraseeda

Documentation fixes
NCSDK-25854

2024-02-27 13:50 UTC, peknis commented
A generic finding in all header files. Many of them start the brief for a function with "Function to do this and that." For example "Function to configure AES..." In my opinion, they should be instead like: "Configure AES..."

2024-02-27 14:00 UTC, peknis requested changes

2024-02-27 14:00 UTC, peknis commented on openthread/include/openthread/thread_ftd.h
> + * it cannot be used, a randomly generated router id is picked. This property can be set only when the device role is
```suggestion
 * it cannot be used, a randomly generated Router ID is picked. This property can be set only when the device role is
```
Not sure whether router needs to be capitalized, but it was in other instances.

2024-02-28 06:49 UTC, peknis approved these changes

2024-02-28 10:12 UTC, divipillai approved these changes

2024-02-28 11:10 UTC, richabp requested changes

2024-02-28 11:10 UTC, richabp commented on nrf_modem/include/nrf_modem_gnss.h
> + *          system time, the expiry times cannot be calculated
```suggestion
 *          system time, the expiry times cannot be calculated.
```

2024-02-28 11:10 UTC, richabp commented on nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
>   * a single instance of an FullMAC based RPU.
```suggestion
 * a single instance of a FullMAC-based RPU.
```

2024-02-28 11:10 UTC, richabp commented on nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_structs.h
>   * a single instance of an FullMAC based RPU.
```suggestion
 * a single instance of a FullMAC-based RPU.
```

2024-02-28 11:10 UTC, richabp commented on openthread/include/openthread/thread_ftd.h
> + * Upon becoming a router or a leader the node attempts to use this router Id. If the preferred router ID is not set
```suggestion
 * Upon becoming a router or a leader, the node attempts to use this router ID. If the preferred router ID is not set
```

2024-02-28 12:22 UTC, edmont commented
We don't modify the `openthread` headers directly, they are updated automatically when creating the libraries based on sources. The proper way to fix doc issues there would be upstream.

2024-02-28 12:26 UTC, umapraseeda commented
> We don't modify the `openthread` headers directly, they are updated automatically when creating the libraries based on sources. The proper way to fix doc issues there would be upstream.

Ok. Tagging @wiba-nordic  for following this up in upstream later. I shall remove the changes to the openthread header files for now.

2024-02-28 12:46 UTC, richabp approved these changes

2024-02-28 14:06 UTC, rugeGerritsen approved these changes
Looked through the changes in ./mpsl and ./softdevice_controller

2024-02-28 21:11 UTC, merged