nrf_wi: Fix TX power issue
nrfconnect/sdk-nrfxlib pull request #1238
Opened 2024-03-01 06:15 UTC by imapa

[SHEL-2533]: The problem of TX output power disparity has been resolved, which occurs when the default power is set without utilizing the TX power command, and the power is explicitly set using the TX power command through the Radio test application.

2024-03-01 06:27 UTC, srkanordic approved these changes

2024-03-01 06:39 UTC, sachinthegreen requested changes

2024-03-01 06:39 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#endif
```suggestion
#endif /* CONFIG_NRF700X_RADIO_TEST */
```

2024-03-01 06:39 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +	prf->temp_volt_backoff.hb_vbt_lt_low = 0;
Why is it needed to set some values to 0 specifically. Why can't `prf` be initialized to all `0` at the beginning of the function and only the specific values updated later in the function?

2024-03-01 06:40 UTC, sachinthegreen requested changes
Please raise manifest PRs too.

2024-03-01 11:25 UTC, sachinthegreen requested changes

2024-03-01 11:25 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#endif
```suggestion
#endif
```
```suggestion
#endif /* ~CONFIG_NRF700X_RADIO_TEST */
```

2024-03-01 11:25 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
> +#endif
```suggestion
#endif /* !CONFIG_NRF700X_RADIO_TEST */
```

2024-03-01 12:40 UTC, sachinthegreen approved these changes

2024-03-05 14:15 UTC, jfischer-no requested changes
Why is there a merge commit?

2024-03-06 06:12 UTC, imapa commented
> Why is there a merge commit?

It happened accidentally. Code is now rebased.

2024-03-06 12:04 UTC, rado17 approved these changes

2024-03-06 12:13 UTC, merged