nrf_modem: add dectphy flavour
nrfconnect/sdk-nrfxlib pull request #1325
Opened 2024-05-07 10:25 UTC by lemrey

Add libmodem dectphy flavour; update documentation.

2024-05-08 07:26 UTC, eivindj-nordic commented on nrf_modem/doc/dectphy.rst
> +It is recommended to use transmission lengths of at most 4-6 slots.
```suggestion
It is recommended to use transmission lengths of at most 4-6 sub-slots.
```

2024-05-08 07:40 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +The DECT NR+ PHY firmware is a variant of the nRF9161 firmware with a different feature set than the cellular firmware.
I have discussed with the other colleagues that we shall call this the `DECT NR+ PHY firmware`, avoiding the term `modem`.

2024-05-08 07:42 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +The DECT physical layer (PHY) interface in the Modem library is used to control the DECT NR+ PHY in the DECT NR+ PHY firmware.
thanks, this is fine as is. I don't differentiate between API and interface, also read https://github.com/nrfconnect/sdk-nrfxlib/pull/1325#discussion_r1593536638

2024-05-08 07:43 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +The very first time the DECT PHY interface is initialized the DECT NR+ PHY firmware will perform a product locking procedure.
Thanks for reminding me, I will check with Jaakko.

2024-05-08 07:45 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +Transmissions take time, that is, they have a length.
It introduces the fact that the length of a transmission has two dimensions, time and size. When talking about the "length of a transmission", you could mean two things, the time it takes to transmit and how much data you are transmitting, which is what this chapter explains.

2024-05-08 08:14 UTC, eivindj-nordic commented on nrf_modem/doc/dectphy.rst
> +Transmissions take time, that is, they have a length.
Ok, thanks for clarifying what you mean by it, though I still find the sentence a bit confusing. 
What about incorporating it in the sentence below
```
The *transmission* length is expressed in sub-slots, where each sub-slot has a size in time, given by the subcarrier scaling factor.
A transmission may take up to 15 sub-slots, where the number of bits per subslot is decided by the chosen modulation scheme. This is shown in the table below.
The length of the *data* being transmitted is expressed in bytes, and is specified by the :c:member:`nrf_modem_dect_phy_tx_params.data_size` parameter.
```

2024-05-08 15:50 UTC, divipillai commented on nrf_modem/doc/dectphy.rst
> +The DECT NR+ PHY firmware is a variant of the nRF9161 firmware with a different feature set than the cellular firmware.
Should we refer as nRF91x1 modem firmware, considering this will be also applicable for nRF9151 as well?

2024-05-08 15:50 UTC, divipillai commented on nrf_modem/doc/dectphy.rst
> +* Convergence layer (CVG), including message flow control, multiplexing and transmission service level control
```suggestion
* Physical layer (PHY).
* Medium Access Control (MAC) layer, including co-existing and channel access operation.
* Data link control (DLC), including routing, segmentation and re-assembly of messages.
* Convergence layer (CVG), including message flow control, multiplexing and transmission service level control.
```

2024-05-10 07:51 UTC, lemrey commented on nrf_modem/doc/CHANGELOG.rst
> +nrf_modem
Not anymore, we will put a number there once we tag NCS.

2024-05-10 10:06 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +DECT NR+ operates on free but regulated radio channels. The availability of the channels and the exact regulation to use them varies in different countries.
ok

2024-05-10 10:06 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +The whole DECT NR+ protocol stack consist of four layers:
ok

2024-05-10 10:06 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +The very first time the DECT PHY interface is initialized the DECT NR+ PHY firmware will perform a product locking procedure.
ok

2024-05-10 10:06 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +* Convergence layer (CVG), including message flow control, multiplexing and transmission service level control
updated!

2024-05-10 10:06 UTC, lemrey commented on nrf_modem/include/nrf_modem_gnss.h
> + *          system time, the expiry times can not be calculated
Let's fix this in `libmodem` repo instead.

2024-05-10 10:20 UTC, divipillai approved these changes

2024-05-10 10:20 UTC, divipillai commented on nrf_modem/doc/dectphy.rst
> +The very first time the DECT PHY interface is initialized the DECT NR+ PHY firmware performs a product locking procedure.
```suggestion
The very first time the DECT PHY interface is initialized, the DECT NR+ PHY firmware performs a product locking procedure.
```
nit

2024-05-10 10:36 UTC, eivindj-nordic approved these changes
Looks good! I think it would be nice with a description of the product locking procedure, though that can be added to the documentation later.

2024-05-10 12:02 UTC, lemrey commented on nrf_modem/doc/dectphy.rst
> +The very first time the DECT PHY interface is initialized the DECT NR+ PHY firmware will perform a product locking procedure.
Updated

2024-05-10 12:03 UTC, lemrey commented on nrf_modem/doc/CHANGELOG.rst
> +* Added new interface for DECT NR+ PHY firmware.
Thanks, updated

2024-05-13 07:48 UTC, merged

2024-05-13 07:50 UTC, nordicjm requested changes

2024-05-13 07:50 UTC, nordicjm commented on nrf_modem/CMakeLists.txt
>      set(float_dir soft-float)
other boards are using lowercase letters, these should be aligned:
```
../nrfxlib/gzll/lib/nrf52810
../nrfxlib/gzll/lib/nrf52811
../nrfxlib/gzll/lib/nrf52820
../nrfxlib/gzll/lib/nrf52832
../nrfxlib/gzll/lib/nrf52833
../nrfxlib/gzll/lib/nrf52840
../nrfxlib/nrf_802154/sl/sl/lib/nrf52833
../nrfxlib/nrf_802154/sl/sl/lib/nrf52840
../nrfxlib/nrf_dm/lib/nrf52832
../nrfxlib/nrf_dm/lib/nrf52833
../nrfxlib/nrf_dm/lib/nrf52840
../nrfxlib/gzll/lib/nrf5340_cpunet
../nrfxlib/nrf_802154/sl/sl/lib/nrf5340_cpunet
../nrfxlib/nrf_dm/lib/nrf5340_cpuapp
../nrfxlib/nrf_dm/lib/nrf5340_cpunet
```

2024-05-13 07:50 UTC, nordicjm commented on nrf_modem/CMakeLists.txt
>      message(FATAL_ERROR "Unknown SOC. Expected (nrf9160, nrf9131, nrf9151, nrf9161), "
this should be using Kconfig symbols instead