doc: Doc check and fixes for 2.7
nrfconnect/sdk-nrfxlib pull request #1381
Opened 2024-06-11 04:57 UTC by umapraseeda

Doc check and fixes for 2.7
Link check + toc check

2024-06-11 05:00 UTC, rugeGerritsen approved these changes
Softdevice controller doc changes are good.

2024-06-11 08:06 UTC, divipillai approved these changes

2024-06-11 08:08 UTC, peknis approved these changes

2024-06-12 08:24 UTC, seko-nordic commented
> Softdevice controller doc changes are good.

I would like to change following bullet:
> * The deprecated functions :c:func:`rand_prio_low_get` and :c:func:`rand_prio_high_get` have been removed.
>   This change does not affect applications developed in the |NCS| context. (DRGN-20473)
to
```
* The deprecated  :c:member:`sdc_rand_source_t.rand_prio_low_get` and :c:member:`sdc_rand_source_t.rand_prio_high_get` have been removed.
  This change does not affect applications developed in the |NCS| context. (DRGN-20473)
```
Otherwise it looks like we removed some APIs provided by SDC. In fact, we removed APIs that were used by SDC, so application needs to provide less now.

2024-06-12 09:50 UTC, umapraseeda commented
> > Softdevice controller doc changes are good.
> 
> I would like to change following bullet here
> 
> https://github.com/nrfconnect/sdk-nrfxlib/blob/0c1d011a1caae8771a764ab72a930903b35fae53/softdevice_controller/CHANGELOG.rst?plain=1#L38
> 
> > * The deprecated functions :c:func:`rand_prio_low_get` and :c:func:`rand_prio_high_get` have been removed.
> 
> to
> 
> ```
> * The deprecated  :c:member:`sdc_rand_source_t.rand_prio_low_get` and :c:member:`sdc_rand_source_t.rand_prio_high_get` have been removed.
> ```
> 
> Otherwise it looks like we removed some APIs provided by SDC. In fact, we removed APIs that were used by SDC, so application needs to provide less now.

Fixed

2024-06-12 10:06 UTC, seko-nordic commented
> Fixed

Thank you, looks good

2024-06-12 10:07 UTC, seko-nordic approved these changes

2024-06-12 10:12 UTC, peknis requested changes

2024-06-12 10:12 UTC, peknis commented on softdevice_controller/CHANGELOG.rst
> +* The deprecated  :c:member:`sdc_rand_source_t.rand_prio_low_get` and :c:member:`sdc_rand_source_t.rand_prio_high_get` have been removed.
```suggestion
* The deprecated :c:member:`sdc_rand_source_t.rand_prio_low_get` and :c:member:`sdc_rand_source_t.rand_prio_high_get` have been removed.
```

2024-06-12 10:43 UTC, KAGA164 approved these changes

2024-06-12 11:36 UTC, peknis commented on softdevice_controller/CHANGELOG.rst
> +* The deprecated  :c:member:`sdc_rand_source_t.rand_prio_low_get` and :c:member:`sdc_rand_source_t.rand_prio_high_get` have been removed.
Now that these structure members are removed, should we just have them between double backticks instead of the current formatting?

2024-06-12 11:59 UTC, peknis approved these changes

2024-06-12 12:03 UTC, lemrey approved these changes

2024-06-12 12:25 UTC, b-gent approved these changes

2024-06-12 15:39 UTC, merged