samples: wifi: radio_test: Add timeout feature for capture mode
nrfconnect/sdk-nrfxlib pull request #1399
Opened 2024-06-26 06:30 UTC by imapa

[SHEL-2811]: Added command to get user-specified timeout in seconds.Rx samples will be displayed only when the capture occurs before the timeout lapses.

2024-07-01 08:17 UTC, sachinthegreen requested changes

2024-07-01 08:17 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
> +	/** Capture timeout in terms of seconds. */
```suggestion
	/** Capture timeout in seconds. */
```

2024-07-01 08:17 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/radio_test/fmac_api.c
> +#define RX_CAPTURE_TIMEOUT_CONST 11
This should be part of FW shared header file?

2024-07-01 08:17 UTC, sachinthegreen commented on nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
> +	/* Capture timeout in terms of seconds. */
```suggestion
	/* Capture timeout in seconds. */
```

2024-07-01 08:17 UTC, sachinthegreen commented on nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
> +	/*! Capture timeout status.
Why `*!` here?

2024-07-09 06:50 UTC, sachinthegreen requested changes

2024-07-09 06:50 UTC, sachinthegreen commented on nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
> +	 *0: Packet detected
```suggestion
	 * 0: Packet detected
```

2024-07-09 06:50 UTC, sachinthegreen commented on nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
> +	 *1: Packet detection failed
```suggestion
	 * 1: Packet detection failed
```

2024-07-11 12:27 UTC, sachinthegreen approved these changes

2024-07-11 12:46 UTC, udaynordic approved these changes

2024-07-11 13:08 UTC, krish2718 requested changes

2024-07-16 06:58 UTC, krish2718 approved these changes

2024-07-16 06:58 UTC, krish2718 commented on nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
> +	unsigned char capture_status;
`cap_status` inline with other params?

2024-08-06 08:14 UTC, merged