nrf_wifi: Option for power save data retrieval
nrfconnect/sdk-nrfxlib pull request #1409
Opened 2024-07-17 07:34 UTC by ajayparida

[SHEL-2947] Option to set either PS-poll or QoS null frame based power save data retrieval mechanism.

2024-07-17 08:37 UTC, sachinthegreen requested changes

2024-07-17 08:37 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
> +enum data_retrieve_frame {
```suggestion
enum ps_data_retrieve_mechanism {
```

2024-07-17 08:37 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
> +	unsigned char ps_data_retrieval_mode;
```suggestion
	unsigned char ps_data_retrieval_mech;
```

2024-07-19 08:19 UTC, sachinthegreen requested changes

2024-07-19 08:19 UTC, sachinthegreen commented on nrf_wifi/fw_if/umac_if/src/cmd.c
> +#else
If you are planning to extend this to also have `Automatic` in the future then shouldn't this be `#else if defined (CONFIG_NRF_WIFI_PS_POLL_BASED_RETRIEVAL)` and then have an else with an error message?

2024-07-25 09:07 UTC, sachinthegreen approved these changes

2024-07-29 09:26 UTC, rado17 approved these changes

2024-07-29 11:09 UTC, merged