bsdlib: version 0.7.8
nrfconnect/sdk-nrfxlib pull request #239
Opened 2020-08-21 07:17 UTC by evenl

Library version: 9aeaf0d8ac582052b21dc45757da934bbea30feb

* Changed UDP sendto retval from ENETDOWN to EBADF is some case when the socket now longer valid.
* Fix issue when modem communication would not work after a shutdown-init sequence.
* Added TLS server support

Signed-off-by: Even Falch-Larsen <even.falch-larsen@nordicsemi.no>

2020-08-21 07:48 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Gitlint issues

5: B1 Line exceeds max length (97>80): "* Changed UDP sendto retval from ENETDOWN to EBADF is some case when the socket now longer valid."
6: B1 Line exceeds max length (83>80): "* Fix issue when modem communication would not work after a shutdown-init sequence."



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-08-25 07:04 UTC, rlubos approved these changes

2020-08-25 08:36 UTC, umapraseeda commented on bsdlib/doc/CHANGELOG.rst
> +* Fix issue when modem communication would not work after a shutdown-init sequence.
```suggestion
* Fixed the issue where the modem communication would not work after a shutdown-init sequence.
```

2020-08-26 07:41 UTC, umapraseeda approved these changes
LGTM

2020-08-26 13:11 UTC, eibe85 approved these changes

2020-08-26 13:18 UTC, lemrey requested changes
We should not return `EBADF` if the socket descriptor was valid. If `socket()` returned a valid descriptor and suddenly it's no longer valid, the application should know what happened to it so that it can the proper steps before attempting to re-open it. In general the descriptor was valid and the application made no mistake in passing it to the API (as opposed to what `EBADF` means, imo).

What situations are we discussing here specifically, i.e. when is a socket no longer valid and we return `EBADF`?

2020-08-27 10:24 UTC, evenl commented
This particular situation is on an open UDP socket when the network do an de-attach and then a re-attach. The IP is now changed and the modem closes the socket automatically. So from the modem side, this socket is invalid. However when I look at the code again all errno codes from the modem for UDP sockets will be converted to BADF. I think we will revert this change and rethink what we should do in this case. I will update the artifact to not contain this change.

2020-08-27 12:25 UTC, evenl commented
Removed EBADF change from the list of changes in this PR.

2020-08-28 07:40 UTC, lemrey approved these changes
Thanks

2020-08-28 10:13 UTC, merged