bsdlib: version 0.8.0
nrfconnect/sdk-nrfxlib pull request #286
Opened 2020-10-07 07:00 UTC by evenl

Library version: 6dad6a3fadb2870f67cccc49292b0722f83b3d84

* Fixed issue with stalled TLS handshake.
* Fixed issue with sendto timeout not working in some cases.
* Fixed issue with TLS connection where connect() hangs.
* Updated the documentation to reflect that NRF_SO_CHIPER_IN_USE is not
currently supported.
* Fixed issue with the AT socket and POLLIN events not happening.
* Add support for PDN authentication parameters.
* Added flushing of the GNSS queue if the stop command is issued.
* Added support for GPS low accuracy use-case.

2020-10-07 07:31 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Identity/Emails issues

abc3140ea4b09586beac172cade335971ed23680: author email (Even Falch-Larsen <even.falch-larsen@nordicsemi.no>) needs to match one of the signed-off-by entries.



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-10-07 11:40 UTC, lemrey requested changes
Hang on, something seems off with the carrier library.

2020-10-07 12:08 UTC, umapraseeda commented on bsdlib/doc/CHANGELOG.rst
> +* Added support for GPS low accuracy use-case.
```suggestion
* Fixed the issue with stalled TLS handshake.
* Fixed the issue with TLS connection where :cpp:func:`nrf_connect` hangs.
* Fixed the issue of sendto timeout not working in some cases.
* Updated the documentation to reflect that NRF_SO_CHIPER_IN_USE is not currently supported.
* Fixed the issue of missing AT socket and POLLIN events.
* Added support for PDN authentication parameters.
* Added flushing of the GNSS socket queue if the stop command is issued.
* Added support for GPS low accuracy use case.
```

2020-10-07 12:08 UTC, umapraseeda commented on bsdlib/doc/CHANGELOG.rst
> +bdli 0.7.8
```suggestion
bsdlib 0.7.8
```

2020-10-09 12:16 UTC, lemrey commented on bsdlib/doc/CHANGELOG.rst
> +* Added support for GPS low accuracy use-case.
Updated

2020-10-09 12:16 UTC, lemrey commented on bsdlib/doc/CHANGELOG.rst
> +bdli 0.7.8
Updated

2020-10-09 12:17 UTC, lemrey commented
@umapraseeda I have updated based on your suggestions, please revist.

2020-10-09 12:27 UTC, rlubos approved these changes

2020-10-09 12:47 UTC, umapraseeda commented
> @umapraseeda I have updated based on your suggestions, please revist.

Thanks.. LGTM!

2020-10-09 12:48 UTC, lemrey commented
Rebased

2020-10-09 12:48 UTC, umapraseeda approved these changes

2020-10-09 12:48 UTC, lemrey approved these changes

2020-10-09 12:48 UTC, lemrey commented
Waiting for https://github.com/nrfconnect/sdk-nrf/pull/3055

2020-10-09 14:05 UTC, merged