Update ZBOSS version with cortex-m33 libs
nrfconnect/sdk-nrfxlib pull request #339
Opened 2020-11-25 14:47 UTC by wbober

This will need an update once dependencies are in.

Depends on https://github.com/nrfconnect/sdk-nrfxlib/pull/332
Depends on https://github.com/nrfconnect/sdk-nrf/pull/3401

2020-11-25 15:08 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Gitlint issues

Commit 87fc2af8b2:
3: B6 Body message is missing

## Identity/Emails issues

87fc2af8b2ca365642fc0bb12c1c6f9cd7410162: author email (Wojciech Bober <wojciech.bober@nordicsemi.no>) needs to match one of the signed-off-by entries.



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-11-30 11:49 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Nits issues

```
Please remove blank lines at end of 'zboss/CHANGELOG.rst'
```



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-11-30 11:50 UTC, greg-fer approved these changes

2020-11-30 12:13 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Nits issues

```
Please remove blank lines at end of 'zboss/CHANGELOG.rst'

Please remove blank lines at end of 'zboss/include/zb_config.h'
```



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-11-30 12:13 UTC, greg-fer requested changes
My commit got lost. The new "Master branch" section in the changelog with the description of the new ZBOSS version is now missing. Please restore it.

2020-11-30 12:47 UTC, NordicBuilder commented
**Some checks failed. Please fix and resubmit.**

## Nits issues

```
Please remove blank lines at end of 'zboss/include/zb_config.h'
```



*Tip: The bot edits this comment instead of posting a new one, so you can check the comment's history to see earlier messages.*

2020-11-30 12:55 UTC, greg-fer approved these changes
Thanks for fixing this, @wbober !

2020-11-30 13:12 UTC, rlubos approved these changes

2020-11-30 13:15 UTC, tomchy approved these changes

2020-11-30 13:47 UTC, tomchy commented
Zigbee CI is green :rocket:

2020-11-30 13:54 UTC, FrancescoSer approved these changes

2020-11-30 17:06 UTC, merged