nrf_802154_sl: Remove FEM support in 802.15.4 SL
nrfconnect/sdk-nrfxlib pull request #352
Opened 2020-12-14 13:19 UTC by JakubPegza

FEM support has been moved to MPSL, obsolete implementation
and API has been removed from this repository

Signed-off-by: Pegza, Jakub <Jakub.Pegza@nordicsemi.no>

2020-12-14 15:07 UTC, czeslawmakarski approved these changes

2020-12-14 15:15 UTC, hubertmis requested changes
Good change. Especially I like reduction of size of the libraries.
I'm only concerned about making documentation files inconsistent with other modules in this repository.

2020-12-14 15:15 UTC, hubertmis commented on nrf_802154_sl/CHANGELOG.rst
> -.. contents::
Should this part be removed? I thought it was added to unify with other libraries.

2020-12-14 15:49 UTC, hubertmis approved these changes
:+1:

2020-12-16 10:48 UTC, hubertmis commented
@FrancescoSer , could you have a look at doc changes in this PR?

2020-12-17 10:24 UTC, FrancescoSer approved these changes

2020-12-17 13:11 UTC, joerchan approved these changes

2020-12-18 14:23 UTC, rlubos approved these changes

2020-12-18 14:23 UTC, merged