Implement ZCL compliant thermostat, fan and thermostat ui attributes
nrfconnect/sdk-nrfxlib pull request #358
Opened 2020-12-21 12:37 UTC by lohisynths

This commit adds ZCL compliant thermostat, fan, and thermostat UI attributes
Changes are based on similar ncs implementations.
Code was tested with ZCL CLI and simple sample code.

2020-12-21 12:49 UTC, lohisynths commented
Is it possible to retrigger Jenkins build?

2021-01-08 15:50 UTC, tomchy requested changes
Hello @lohisynths!
Thank you for your work and submitting the PR!
The Jenkins build has failed due to the commit author validation check.
I am glad that you have modified only those files that are not updated through the ZBOSS release process, so no additional merges in the future will be needed.

I've left some comments after checking your definitions against the ZCL specification.
Additionally, in order to run the CI, the second branch on the [sdk-nrf](https://github.com/nrfconnect/sdk-nrf) repository is needed, updating the `west.yml` file, so it points to the PR in nrfxlib. I can make it for you, if you like.

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_ui_addons.h
> +    uint8_t schedule_programming_visibility;
The `ScheduleProgrammingVisibility` attribute is optional, thus it is not required by the `ZB_ZCL_DECLARE_THERMOSTAT_UI_CONFIG_ATTRIB_LIST` macro.
Generally, the full list of attributes should have `attrs_ext_t` suffix and be passed to the macro with `ATTRIB_LIST_EXT` suffix.

Do you use the `schedule_programming_visibility` field? If so, could you provide macro definitions for the extended variant?
- `ZB_ZCL_DECLARE_THERMOSTAT_UI_CONFIG_ATTRIB_LIST_EXT`
- `ZB_SET_ATTR_DESCR_WITH_ZB_ZCL_ATTR_THERMOSTAT_UI_CONFIG_SCHEDULE_PROGRAMMING_VISIBILITY_ID`

If not, please simply remove this field or rename the type definition :slightly_smiling_face:

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_addons.h
> +    zb_int16_t PI_cooling_demand;
The PICoolingDemand field has an `uint8` type.

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_addons.h
> +    zb_int16_t PI_heating_demand;
The PIHeatingDemand field has an `uint8` type.

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_addons.h
> +} zb_zcl_thermostat_info_attrs_t;
This list goes to the `ATTRS_LIST_EXT` macro, thus should have the `attrs_ext_t` suffix.

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_addons.h
> +} zb_zcl_thermostat_settings_attrs_t;
This list goes to the `ATTRS_LIST_EXT` macro, thus should have the `attrs_ext_t` suffix.

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_addons.h
> +} zb_zcl_thermostat_schedule_and_HVAC_attrs_t;
This list goes to the `ATTRS_LIST_EXT` macro, thus should have the `attrs_ext_t` suffix.

2021-01-08 15:50 UTC, tomchy commented on zboss/include/addons/zcl/zb_zcl_thermostat_addons.h
> +#endif /* ZB_ZCL_THERMOSTAT_ADDONS_H__ */
General: I do agree with you. Even though the `ZB_ZCL_DECLARE_THERMOSTAT_ATTRIB_LIST_EXT` macro does not require all fields to be present, it is better to provide a complete list in type definitions.

2021-01-13 19:56 UTC, tomchy commented
Hello @lohisynths!
Is it OK for you if I take over this PR, fix it and merge from my sdk-nrfxlib fork?
Unfortunately, by going this path, you will not be credited for the contribution, but we will be able to merge this under the current rules of contribution.

When it comes to the comments, I propose to resolve them in this PR. Please leave your feedback, if you disagree with my notes.

2025-03-20 08:14 UTC, closed without merging

2025-03-20 08:15 UTC, NordicBuilder commented
none

*Note: This comment is automatically posted and updated by the Contribs GitHub Action.*