Add braces around ARM_MBEDTLS_PATH in nrf_security/CMakeLists.txt
nrfconnect/sdk-nrfxlib pull request #384
Opened 2021-01-27 11:47 UTC by bamkrs

Otherwise the string "ARM_MBEDTLS_PATH" gets passed to `get_mbedtls_dir` instead the value of the variable `ARM_MBEDTLS_PATH`.
Without the braces, its not possible to pass the actual path to `get_mbedtls_dir`.

2021-01-27 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=384) before we can accept your contribution.<br/><hr/>**Benedikt-Alexander Mokroß** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrfxlib?pullRequest=384) it.</sub>

2021-02-03 13:16 UTC, tejlmand requested changes
Thanks a lot for pointing out this issue.

> Otherwise the string "ARM_MBEDTLS_PATH" gets passed to get_mbedtls_dir instead the value of the variable ARM_MBEDTLS_PATH.
> Without the braces, its not possible to pass the actual path to get_mbedtls_dir.

The problem is not with the braces, as those must not be there, as we are returning a value (hence the `PARENT_SCOPE`).
https://github.com/nrfconnect/sdk-nrfxlib/blob/9017da739a02e51a3e152df8d2efc62bb4111b2f/common.cmake#L64

Instead the problem was that the function argument name hides the value of the real variable.
This is now fixed here:
https://github.com/nrfconnect/sdk-nrfxlib/pull/396

2021-02-03 13:35 UTC, bamkrs commented
> Instead the problem was that the function argument name hides the value of the real variable.
> This is now fixed here:
> #396

Oh, so I just misunderstood the intention of the function! Now this is making a lot more sense. Thanks for fixing it!

2021-02-03 13:35 UTC, closed without merging

2021-02-04 20:33 UTC, tejlmand commented
> Thanks for fixing it!

And thanks for finding it.