Update zboss libraries to v3.5.0.0+1.0.0
nrfconnect/sdk-nrfxlib pull request #409
Opened 2021-02-15 10:31 UTC by tomchy

2021-02-15 11:24 UTC, rlubos approved these changes

2021-02-15 13:25 UTC, tomchy commented
Removed DNM: It's been decided to stay with the `Production` and `Development` nomenclature and remove the `Production` variant for `nRF5340`.

2021-02-15 14:03 UTC, wbober approved these changes

2021-02-15 14:03 UTC, wbober commented on zboss/CHANGELOG.rst
> +* Additional ZBOSS stack library version based on the ZBOSS build v3.5.0.0.
```Additional``` --> ```Development```?

2021-02-15 14:03 UTC, wbober commented on zboss/CHANGELOG.rst
> +* Updated ZBOSS stack to version ``3.3.0.6+11_30_2020``.
```Updated production ZBOSS stack library version```?

2021-02-15 15:59 UTC, ru-fu requested changes

2021-02-15 15:59 UTC, ru-fu commented on zboss/CHANGELOG.rst
> +  This library version is dedicated for :ref:`NCP development <nrf:ug_zigbee_platform_design_ncp_details>`
```suggestion
  This library version is dedicated for :ref:`NCP development <nrf:ug_zigbee_platform_design_ncp_details>`.
```

2021-02-15 15:59 UTC, ru-fu commented on zboss/CHANGELOG.rst
> +* The development libraries were also built for the Cortex-M33 CPU.
```suggestion
* Development libraries for the Cortex-M33 CPU.
```

2021-02-15 15:59 UTC, ru-fu commented on zboss/CHANGELOG.rst
> +* Updated ZBOSS stack to version ``3.3.0.6+11_30_2020``.
```suggestion
* Updated the production ZBOSS stack to version ``3.3.0.6+11_30_2020``.
```

2021-02-15 15:59 UTC, ru-fu commented on zboss/README.rst
>    This version is enabled with the :option:`CONFIG_ZIGBEE_LIBRARY_PRODUCTION` KConfig option and its files are located in the :file:`zboss/production/` directory.
```suggestion
  This version is enabled with the :option:`CONFIG_ZIGBEE_LIBRARY_PRODUCTION` Kconfig option and its files are located in the :file:`zboss/production/` directory.
```

2021-02-15 15:59 UTC, ru-fu commented on zboss/README.rst
> +  See compatibility matrix for certification status of the production library present in a given NCS release.
```suggestion
  See the compatibility matrices in the `Infocenter`_ for the certification status of the production library that is present in a given |NCS| release.
```

2021-02-15 15:59 UTC, ru-fu commented on zboss/doc/zboss_configuration.rst
>  The ZBOSS production library version is enabled by default with the :option:`CONFIG_ZIGBEE_LIBRARY_PRODUCTION` KConfig option.
```suggestion
The ZBOSS production library version is enabled by default with the :option:`CONFIG_ZIGBEE_LIBRARY_PRODUCTION` Kconfig option.
```

2021-02-15 15:59 UTC, ru-fu commented on zboss/README.rst
> +  The production libraries fully conform to the certification, but they are not necessarily certified.
I suggest to start a new paragraph here and in line 15/17 (before "This version might not conform ...").

2021-02-15 15:59 UTC, ru-fu commented on zboss/doc/zboss_configuration.rst
> +     - nRF52840 Single SoC
```suggestion
     - nRF5340 single SoC
     - nRF5340 NCP
     - nRF52833 single SoC
     - nRF52833 NCP
     - nRF52840 single SoC
```

2021-02-15 16:29 UTC, ru-fu approved these changes

2021-02-16 09:05 UTC, shantha-14 approved these changes

2021-02-16 09:05 UTC, merged