softdevice_controller: rev c5a8a5af402963933cbe3c33fe19f63ced0a2297
nrfconnect/sdk-nrfxlib pull request #439
Opened 2021-03-17 15:36 UTC by balaji-nordic

CHANGELOG.rst contains the list of changes.

Signed-off-by: 'Balaji Srinivasan' <basr@nordicsemi.no>

2021-03-17 15:41 UTC, joerchan commented
@balaji-nordic Looks OK, not sure what compliance is complaining about, but might be because it is a draft.

You will need a manifest update PR in sdk-nrf as well.

2021-03-17 15:47 UTC, rugeGerritsen approved these changes

2021-03-17 16:29 UTC, ru-fu requested changes

2021-03-17 16:29 UTC, ru-fu commented on softdevice_controller/CHANGELOG.rst
> +v1.5-branch
```suggestion
nRF Connect SDK v1.5.1
```
I don't think it makes sense to mention the v1.5 branch here - we don't tell users to use version branches (only tags or master).
(Also add *** as needed in the next line.)

2021-03-17 16:29 UTC, ru-fu commented on softdevice_controller/CHANGELOG.rst
> +========
```suggestion
Bug fixes
=========
```
Usage has changed.

2021-03-18 08:54 UTC, ru-fu reviewed
Docs look good now, but need to squash the commits.

2021-03-18 09:58 UTC, balaji-nordic commented
> @balaji-nordic Looks OK, not sure what compliance is complaining about, but might be because it is a draft.
> 
> You will need a manifest update PR in sdk-nrf as well.

https://github.com/nrfconnect/sdk-nrf/pull/4182 created for this.

2021-03-18 10:08 UTC, balaji-nordic commented
> Docs look good now, but need to squash the commits.

Squashed the commits now.

2021-03-18 10:21 UTC, ru-fu approved these changes

2021-03-22 07:48 UTC, joerchan approved these changes

2021-03-22 07:48 UTC, merged