zboss: Distribute BDB and ZCL layers in sources
nrfconnect/sdk-nrfxlib pull request #473
Opened 2021-05-28 12:40 UTC by tomchy

The BDB and ZCL layer implementation is now available in sources and
extracted from the main ZBOSS static library.

Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>

2021-06-01 13:28 UTC, tomchy commented
Testing of the ZBOSS library is currently being finalized. Afterwards - there will be a library and ZBOSS version name update, but the rest of the PR will remain unchanged.

I will remove the DNM label after the ZBOSS update.

2021-06-02 10:19 UTC, sebastiandraus approved these changes

2021-06-02 11:24 UTC, tomchy commented on zboss/include/osif/build_info.h
> +#define ZBOSS_BUILD_TAG "5dcb873b0"
Yes, it is not tagged right now.

2021-06-02 13:14 UTC, rlubos approved these changes

2021-06-02 15:37 UTC, tomchy commented on zboss/include/osif/build_info.h
> +#define ZBOSS_BUILD_TAG "5dcb873b0"
Updated

2021-06-02 15:39 UTC, tomchy commented
ZBOSS updated. Ready for merges.

2021-06-07 08:18 UTC, b-gent requested changes

2021-06-07 08:18 UTC, b-gent commented on zboss/CHANGELOG.rst
> +* Moved scheduler API prototypes to zb_osif.h
```suggestion
* Moved scheduler API prototypes to :file:`zb_osif.h`.
```

2021-06-07 08:18 UTC, b-gent commented on zboss/CHANGELOG.rst
> +* Extended NCP protocol by Inter-PAN commands
```suggestion
* Extended NCP protocol with inter-PAN commands.
```

2021-06-07 08:18 UTC, b-gent commented on zboss/CHANGELOG.rst
> +* Added API for sending and receiving Inter-PAN frames
```suggestion
* Added API for sending and receiving inter-PAN frames.
```

2021-06-07 08:18 UTC, b-gent commented on zboss/CHANGELOG.rst
> +* Added bootloader commands in the NCP protocol
```suggestion
* Added bootloader commands in the NCP protocol.
```

2021-06-07 08:18 UTC, b-gent commented on zboss/CHANGELOG.rst
> +* Added sources of the BDB and ZCL layers and removed them from the main ZBOSS library
```suggestion
* Added sources of the BDB and ZCL layers and removed them from the main ZBOSS library.
```

2021-06-07 08:50 UTC, tomchy commented on zboss/CHANGELOG.rst
> +* Moved scheduler API prototypes to zb_osif.h
Fix applied.

2021-06-07 08:51 UTC, b-gent approved these changes

2021-06-08 07:05 UTC, merged

2021-06-08 09:41 UTC, tejlmand commented
@rlubos why was this merged when CI for manifest PR is red ?
![image](https://user-images.githubusercontent.com/9802583/121162658-686e5e80-c84e-11eb-98d5-9282ac150030.png)