Bluetooth: Mesh: Switch default BLE controller for mesh to SDC
nrfconnect/sdk-nrfxlib pull request #475
Opened 2021-05-31 12:42 UTC by PavelVPV

Run Bluetooth mesh in NCS with SoftDevice Controller by default.

Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>

2021-05-31 12:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=475) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrfxlib?pullRequest=475) it.</sub>

2021-05-31 12:45 UTC, joerchan commented on softdevice_controller/Kconfig
> +	default BT_LL_SW_SPLIT
You would be changing the default for non-mesh. So if you are removing the mesh default to SPLIT it should look like this:
```suggestion
	default BT_LL_SOFTDEVICE
```

2021-05-31 12:46 UTC, joerchan requested changes
Wrong default for non-mesh.

2021-05-31 13:06 UTC, joerchan approved these changes

2021-05-31 13:34 UTC, Balaklaka approved these changes

2021-08-25 14:30 UTC, trond-snekvik approved these changes

2021-08-25 14:31 UTC, rugeGerritsen approved these changes

2021-08-25 14:36 UTC, merged