doc: doc fixes related to NCSDK-9787
nrfconnect/sdk-nrfxlib pull request #510
Opened 2021-06-28 12:38 UTC by umapraseeda

Remove occurences of 'please' from NCS docs
ref: NCSDK-9787

Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>

2021-06-28 12:55 UTC, peknis requested changes

2021-06-28 12:55 UTC, peknis commented on crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst
> +   Hence, use a newer version.
Change the warning to a note. You remember, no warnings unless someone's health or life is at risk.

2021-06-28 12:55 UTC, peknis commented on softdevice_controller/README.rst
Why not just a note as follows:

`.. note::`
    Low Latency Packet mode is not supported on the nRF53 Series.

2021-06-28 12:55 UTC, peknis commented on crypto/nrf_cc310_platform/CHANGELOG.rst
> +See :FILE:`include/nrf_cc3xx_platform_ctr_drbg.h`.
FILE -> file

2021-06-28 12:55 UTC, peknis commented on crypto/nrf_cc310_platform/CHANGELOG.rst
> +Added new version of libraries nrf_cc310_platform/nrf_cc312_platform built with mbed TLS version 2.23.0.
```suggestion
Added new version of libraries nrf_cc310_platform/nrf_cc312_platform built with Mbed TLS version 2.23.0.
```

2021-06-29 07:51 UTC, umapraseeda commented on crypto/nrf_cc310_platform/CHANGELOG.rst
> +Added new version of libraries nrf_cc310_platform/nrf_cc312_platform built with mbed TLS version 2.23.0.
will be fixed in PR:509

2021-06-29 08:02 UTC, peknis approved these changes

2021-06-29 08:23 UTC, greg-fer approved these changes

2021-06-29 08:34 UTC, joerchan approved these changes

2021-06-29 08:42 UTC, rugeGerritsen approved these changes
SDC changes are ok.

2021-06-30 16:45 UTC, merged