nrf_modem: release v1.4.0
nrfconnect/sdk-nrfxlib pull request #577
Opened 2021-11-03 11:34 UTC by lemrey

Modem library release v1.4.0.

_commits to be fixed-up_

2021-11-03 13:07 UTC, balaji-nordic commented
Dont we need an some explanations for the new `nrf_modem_os*` functions in `ug_nrf_modem_porting_os.rst`?

2021-11-03 15:20 UTC, lemrey commented
Thanks @balaji-nordic, I have updated the porting guide with a brief description for each function.

2021-11-10 13:57 UTC, lemrey commented
Squashed all commits

2021-11-18 10:15 UTC, rlubos requested changes
Why did the lib size increase that much?
```
BIN +8.37 MB (5700%) nrf_modem/lib/cortex-m33/hard-float/libmodem.a
````
I don't think we should merge it like this.

2021-11-22 08:54 UTC, umapraseeda commented on nrf_modem/doc/CHANGELOG.rst
> +* Added support for GNSS A-GPS data need query.
```suggestion
* Added support for checking when A-GPS data is needed.
```

2021-11-23 09:53 UTC, eivindj-nordic commented on nrf_modem/doc/pdn.rst
> +Configuring a network socket to a use a PDN
"...to use a..."

2021-11-23 09:53 UTC, eivindj-nordic commented on nrf_modem/include/nrf_modem_gnss.h
> +/** @brief A-GPS data need and expiry times.
This sentence is unclear.

2021-11-23 13:37 UTC, lemrey reviewed
@rlubos thanks for checking, the change is intentional. The increased size is because the library now contains debugging symbols.
There is a line in the release notes about that.

2021-11-23 14:14 UTC, tokangas commented
> Would A-GPS data expiry work, @tokangas?

@lemrey Yes, that's fine with me.

2021-11-24 08:17 UTC, umapraseeda approved these changes

2021-11-25 15:45 UTC, rlubos approved these changes
Lifting my -1, but IMO we should really reconsider our strategy regarding library releases in the future. Putting dozens of megabytes on each library release will increase the repository size greatly.

2021-11-25 15:48 UTC, merged