nrf_modem: release v1.0.1-1
nrfconnect/sdk-nrfxlib pull request #605
Opened 2021-12-08 11:58 UTC by lemrey

- Fixed a bug where stopping GNSS via NRF_SO_GNSS_STOP
  would let any ongoing nrf_recv() calls on the GNSS socket
  block indefinitely.

@peknis, could you please have a look at the changelog entry?

2021-12-08 12:08 UTC, peknis requested changes

2021-12-08 12:08 UTC, peknis commented on nrf_modem/doc/CHANGELOG.rst
> +* Fixed a bug where stopping GNSS via ``NRF_SO_GNSS_STOP`` would let any ongoing :c:func:`nrf_recv` calls on the GNSS socket block indefinitely.
```suggestion
* Fixed a bug where stopping GNSS using ``NRF_SO_GNSS_STOP`` would let any ongoing :c:func:`nrf_recv` calls on the GNSS socket block indefinitely.
```

2021-12-08 12:29 UTC, shantha-14 approved these changes

2021-12-08 12:29 UTC, peknis approved these changes

2021-12-09 12:52 UTC, thst-nordic approved these changes

2021-12-09 13:12 UTC, merged