doc: nrf_modem: updates to delta DFU
nrfconnect/sdk-nrfxlib pull request #610
Opened 2021-12-15 14:33 UTC by lemrey

Update the delta DFU documentation with flow charts for both the update and rollback operations. Other minor updates.

2021-12-16 06:18 UTC, jarlamsa approved these changes
LGTM

2021-12-16 07:45 UTC, Avalei commented
It looks like the figures may have been made using an older template. I went ahead and committed an update using our current figure template so that they would be size and style-compliant.

2021-12-16 07:46 UTC, Avalei approved these changes

2021-12-16 08:40 UTC, lemrey commented
Compliance issues will disappear after we squash the commits.

2021-12-16 08:47 UTC, peknis requested changes

2021-12-16 08:47 UTC, peknis commented on nrf_modem/doc/delta_dfu.rst
> +   :alt: Modem delta DFU update flowchart
```suggestion
.. figure:: images/delta_dfu_update.svg
   :alt: Modem delta DFU update flowchart
   
   Modem delta DFU update flowchart
```
This adds the caption.

2021-12-16 08:47 UTC, peknis commented on nrf_modem/doc/delta_dfu.rst
> +   :alt: Modem delta DFU rollback flowchart
```suggestion
.. figure:: images/delta_dfu_rollback.svg
   :alt: Modem delta DFU rollback flowchart
   
   Modem delta DFU rollback flowchart
```
Adding the caption.

2021-12-16 08:47 UTC, peknis commented on nrf_modem/doc/delta_dfu.rst
> +The application can verify that by reading the modem firmware UUID or reading the ``AT+CGMR`` command response.
```suggestion
The application can verify that by reading the modem firmware UUID or the ``AT+CGMR`` command response.
```

2021-12-16 08:47 UTC, peknis commented on nrf_modem/doc/delta_dfu.rst
> +Regardless of the value returned by :c:func:`nrf_modem_init`, the application must reinitialize the modem by reinitializing the Modem library in order to run the modem firmware.
```suggestion
Regardless of the value returned by :c:func:`nrf_modem_init`, the application must reinitialize the modem by reinitializing the :ref:`nrf_modem` to run the modem firmware.
```

2022-01-06 08:48 UTC, lemrey commented
@peknis I have committed your suggestions

2022-01-07 06:38 UTC, peknis approved these changes

2022-02-02 17:10 UTC, lemrey commented
I picked this commit in #634

2022-02-02 17:10 UTC, closed without merging