doc: nrf_modem: improve GNSS documentation
nrfconnect/sdk-nrfxlib pull request #706
Opened 2022-03-30 14:45 UTC by tokangas

Added a note that GNSS needs to be enabled before it can be configured or started.

Clarified when GNSS priority mode is automatically disabled.

2022-03-31 05:31 UTC, peknis requested changes

2022-03-31 05:31 UTC, peknis commented on nrf_modem/doc/gnss_interface.rst
> +   Before GNSS module can be configured or started, GNSS must be enabled in modem system mode and activated in modem functional mode.
How about in more active mode? Something like this:
You need to enable GNSS in modem system mode and activate it in modem functional mode before starting or configuring the GNSS module.

2022-03-31 05:31 UTC, peknis commented on nrf_modem/doc/gnss_interface.rst
> +Priority mode is disabled automatically after producing the first fix or after 40 seconds.
```suggestion
Priority mode is disabled automatically after the first fix or after 40 seconds.
```

2022-03-31 08:56 UTC, lemrey approved these changes

2022-03-31 08:58 UTC, peknis approved these changes

2022-03-31 09:30 UTC, tokangas commented
> Not entirely sure whether this deserves an entry in the changelog.

Has there usually been changelog entries for documentation improvements?

2022-03-31 09:35 UTC, peknis commented
> Has there usually been changelog entries for documentation improvements?

Oh, I did not realize first this was in nrfxlib docs. Maybe we are okay without a changelog entry.

2022-04-01 13:04 UTC, rlubos approved these changes

2022-04-01 13:04 UTC, merged