Zigbee: Update ZBOSS libraries
nrfconnect/sdk-nrfxlib pull request #719
Opened 2022-04-22 12:53 UTC by FilipZajdel

2022-04-27 08:44 UTC, tomchy requested changes

2022-04-27 08:44 UTC, tomchy commented on zboss/development/src/CMakeLists.txt
> -
Please bring it back :)

2022-04-27 08:44 UTC, tomchy commented on zboss/production/src/CMakeLists.txt
> -# Prevent the -Waddress-of-packed-member warning. We appear to be
Please bring it back too :)

2022-05-04 07:38 UTC, tomchy approved these changes

2022-05-04 07:41 UTC, greg-fer commented on zboss/CHANGELOG.rst
> +* Updated ZCL in all variants of ZBOSS to specification version ``8``.
```suggestion
* Updated ZCL in all variants of ZBOSS to specification version 8.
```

2022-05-04 07:41 UTC, greg-fer commented on zboss/CHANGELOG.rst
> +  The sample device definitions can be found inside the ``include`` directory in every Zigbee sample and application.
```suggestion
  The sample device definitions can be found inside the :file:`include` directory in every Zigbee sample and application.
```

2022-05-04 07:41 UTC, greg-fer commented on zboss/CHANGELOG.rst
> +* Fixed an issue where incorrect Read Attributes Response is sent on reading multiple attributes when the first attribute is unsupported.
```suggestion
* Fixed an issue where incorrect Read Attributes Response would be sent on reading multiple attributes when the first attribute is unsupported.
```

2022-05-04 13:20 UTC, greg-fer approved these changes
Approving, but please contact me so that we can coordinate uploading the docs with the merge of this PR.

2022-05-04 14:37 UTC, merged