openthread: update libraries based on commit 130afd9
nrfconnect/sdk-nrfxlib pull request #753
Opened 2022-05-26 06:19 UTC by lmaciejonczyk

Update OpenThread pre-build libraries.

2022-05-26 06:39 UTC, edmont requested changes
Master variant is missing for cortex-m4.

2022-05-26 07:37 UTC, edmont approved these changes

2022-05-26 10:26 UTC, edmont commented
Manifest CI is green.

2022-05-26 13:35 UTC, rlubos approved these changes

2022-05-27 07:18 UTC, canisLupus1313 approved these changes

2022-05-27 11:40 UTC, merged