softdevice_controller: production support for CTE AoA TX
nrfconnect/sdk-nrfxlib pull request #755
Opened 2022-05-26 10:14 UTC by yuxCai

Remove "experimental support for AoA" in README
and CHANGELOG

Signed-off-by: Yuxuan Cai <yuxuan.cai@nordicsemi.no>

2022-05-26 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=755) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nrfconnect/sdk-nrfxlib?pullRequest=755) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nrfconnect/sdk-nrfxlib?pullRequest=755) it.</sub>

2022-05-26 17:25 UTC, Tschet1 approved these changes

2022-05-27 05:40 UTC, wiba-nordic approved these changes

2022-05-27 08:10 UTC, b-gent requested changes

2022-05-27 08:10 UTC, b-gent commented on mpsl/doc/bluetooth_coex.rst
> +.. NOTE::
pls change to lower case

2022-05-27 08:22 UTC, b-gent approved these changes

2022-05-27 08:22 UTC, b-gent commented
Ready to merge.

2022-05-27 09:00 UTC, merged