cmake: crypto: Support for building with out of tree cc3xx libaries
nrfconnect/sdk-nrfxlib pull request #839
Opened 2022-10-07 10:27 UTC by mswarowsky

This enables to easily build with out of tree version of the cc3xx runtime library, by setting the env variable CUSTOM_CC3XX_BUILD_PATH It should point to the folder that includes a nrf_{CC3XX_ARCH}_platform and nrf_{CC3XX_ARCH}_mbedcrypto folder with all the files normally provided by nrfxlib.

Ref: NCSDK-17366

Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

2022-10-07 10:42 UTC, vili-nordic approved these changes

2022-10-12 08:51 UTC, tejlmand requested changes

2022-10-12 08:51 UTC, tejlmand commented on crypto/CMakeLists.txt
> +  if (DEFINED ENV{CUSTOM_CC3XX_BUILD_PATH})
we should not suddenly check for an environment variable that suddenly change the code path.

This setting is not documented anywhere, and if we start using this principle here then other part of the NCS codebase will soon copy this principle to other places, making it much harder to understand how to use / configure NCS.

Please ping directly for discussion of alternative solutions depending on exact needs.

2022-10-12 11:00 UTC, mswarowsky commented
Based on the feedback for Torsten, gonna close this and work on a solution that is more streamlined with the rest of nrfxlib

2022-10-12 11:00 UTC, closed without merging