nrf_security: Add sanity check for psa key attributes
nrfconnect/sdk-nrfxlib pull request #841
Opened 2022-10-10 13:17 UTC by mswarowsky

When calling psa_generate_key/import_key/copy_key an key attributes description is passed, wich contains values like, key_type, key_algorithm, etc. This adds a sanity check to ensure key type, algorithm and size are a valid combination according to the psa crypto spec.

Ref: NCSDK-17103

Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

2022-10-10 13:44 UTC, vili-nordic reviewed
looks ok to me. Some spelling errors.

Commit message:
*an key
*wich

2022-10-10 13:44 UTC, vili-nordic commented on nrf_security/src/psa_crypto_driver_wrappers.c
> + * @brief Compare AEAD alogrithms, by ingoring the the output tag length
algorithms. ignoring

2022-10-10 13:44 UTC, vili-nordic commented on nrf_security/src/psa_crypto_driver_wrappers.c
> + * @brief Checks if the given algorithm is one the follwing ECDSA algorithms
following

2022-10-10 13:44 UTC, vili-nordic commented on nrf_security/src/psa_crypto_driver_wrappers.c
> + *  is a valid tuple by the PSA standart
standart

2022-10-10 14:24 UTC, vili-nordic approved these changes

2022-10-11 10:42 UTC, Vge0rge requested changes

2022-10-11 10:42 UTC, Vge0rge commented on nrf_security/src/psa_crypto_driver_wrappers.c
> +    return (GET_ALG_BASE(algorithm) == PSA_ALG_DETERMINISTIC_ECDSA_BASE  ||
I think that it is better to use the defined macros from PSA.
Look at: PSA_ALG_ECDSA_IS_DETERMINISTIC(alg)
PSA_ALG_IS_ECDSA(alg)
PSA_ALG_IS_ECDH(alg)

They are basically doing the same thing.

2022-10-11 10:42 UTC, Vge0rge commented on nrf_security/src/psa_crypto_driver_wrappers.c
> + * @return psa_status_t psa_status_t PSA_ERROR_INVALID_ARGUMENT if invalid else PSA_SUCCESS
Remove one psa_status_t

2022-10-11 10:42 UTC, Vge0rge commented on nrf_security/src/psa_crypto_driver_wrappers.c
> +            if(GET_ALG_BASE(algorithm) == PSA_ALG_HKDF_BASE ||
There is a macro for and for the TLS12 functions.
You can grep "PSA_ALG_IS" in the include/psa/ and you will see all the available macros.

2022-10-11 10:48 UTC, vili-nordic commented on nrf_security/src/psa_crypto_driver_wrappers.c
> + * @brief Compare AEAD alogrithms ingoring the the output tag length
and alogrithms
and ingoring

2022-10-17 08:12 UTC, vili-nordic commented on nrf_security/src/psa_crypto_driver_wrappers.c
> + * @brief Compare AEAD alogrithms and ingoring the output tag length
* algorithms
* ignoring

2022-10-18 11:29 UTC, frkv approved these changes
LGTM

2022-11-21 13:25 UTC, closed without merging