nrf_802154: Update revision of nrf_802154
nrfconnect/sdk-nrfxlib pull request #912
Opened 2023-02-14 14:02 UTC by ahasztag

This PR updates revision of the nrf_802154 component to commit 2079d8bd247176af6d9324da242fb97d48bfa617 of the sdk-nrf-802154

2023-02-14 14:04 UTC, czeslawmakarski approved these changes

2023-02-14 14:05 UTC, jciupis approved these changes

2023-02-14 14:13 UTC, FrancescoSer approved these changes
Approved by please fix the small issue highlighted in the comment

2023-02-14 14:13 UTC, FrancescoSer commented on nrf_802154/doc/CHANGELOG.rst
> +* Added the  possibility to disable the continuous and modulated carrier functions by setting the NRF_802154_CARRIER_FUNCTIONS_ENABLED define to 0.
```suggestion
* Added the possibility to disable the continuous and modulated carrier functions by setting the NRF_802154_CARRIER_FUNCTIONS_ENABLED define to 0.
```

2023-02-14 14:40 UTC, ahasztag commented on nrf_802154/doc/CHANGELOG.rst
> +* Added the  possibility to disable the continuous and modulated carrier functions by setting the NRF_802154_CARRIER_FUNCTIONS_ENABLED define to 0.
Done

2023-02-15 06:42 UTC, ankuns requested changes
Bad sha in commit message:
there is no `7f5cb04aa26937d61995d91c0439b70f35e14186` in sdk-nrf-802154,
shouldn't it be `122a8380f9d58cc1fccd2736c917769bdae72c5d` ?
The same in manifest PR https://github.com/nrfconnect/sdk-nrf/pull/10275

2023-02-15 07:33 UTC, ahasztag commented
> Bad sha in commit message: there is no `7f5cb04aa26937d61995d91c0439b70f35e14186` in sdk-nrf-802154, shouldn't it be `122a8380f9d58cc1fccd2736c917769bdae72c5d` ? The same in manifest PR [nrfconnect/sdk-nrf#10275](https://github.com/nrfconnect/sdk-nrf/pull/10275)

Fixed

2023-02-15 07:38 UTC, ankuns approved these changes

2023-02-15 10:01 UTC, merged